Generate test report

diff --git a/.github/workflows/unit-test-run.yaml b/.github/workflows/unit-test-run.yaml
--- a/.github/workflows/unit-test-run.yaml
+++ b/.github/workflows/unit-test-run.yaml
@@ -7,6 +7,9 @@ on:
 
 jobs:
   run-tests:
+    env:
+      BUILD_CONFIG: 'Release'
+      SOLUTION: './AcademyCleanTesting.sln'
     runs-on: ubuntu-latest
     
     services:
@@ -35,10 +38,19 @@ jobs:
         run: docker --version
 
       - name: .NET Restore
-        run: dotnet restore ./AcademyCleanTesting.sln
+        run: dotnet restore $SOLUTION 
 
       - name: .NET Build
-        run: dotnet build ./AcademyCleanTesting.sln --no-restore
+        run: dotnet build $SOLUTION --no-restore --configuration $BUILD_CONFIG
 
       - name: .NET Test
-        run: dotnet test ./tests/Application.Integration.Tests
+        run: dotnet test ./tests/Application.Integration.Tests --configuration $BUILD_CONFIG
+      
+      - name: Generate Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: DotNET Test Report
+          path: "**/test-results.trx"                            
+          reporter: dotnet-trx
+          fail-on-error: true
